@version: 4.10
source s_net { udp(ip("0.0.0.0") port(514)); };
template t_bunkerweb { template("$MSG\n"); template_escape(no); };
destination d_bunkerweb { file("/var/log/bunkerweb/access.log" template(t_bunkerweb) owner("101") group("101") perm(0440) dir_perm(0770) create_dirs(yes)); };
log { source(s_net); destination(d_bunkerweb); flags(flow-control); };
